---
- hosts: sonarr
  become: yes
  vars:
      nfsmounts:
        - {  path: "/mnt/series", src: "10.4.9.2:/opt/share/series" }
        - {  path: "/mnt/torrent", src: "10.4.9.2:/opt/share/torrent" }
  tasks:
    - name: Install nfs-common
      apt:
        name: nfs-common
        state: present

    - name: Make mount point series Libary
      file:
        path: /mnt/series
        state: directory
        mode: 777
    
    - name: Make mount point torrent libary
      file:
        path: /mnt/torrent
        state: directory
        mode: 777

    - name: mount the nfsshare in client side
      mount:
        fstype: nfs
        opts: rw,async,hard,intr,noexec
        state: mounted
        src: "{{ item.src }}"
        path: "{{ item.path }}"
      with_items: "{{nfsmounts}}"

    - name: Make series Libary readable
      file:
        path: /mnt/series
        state: directory
        mode: 777
    
    - name: Make torrent libary readable
      file:
        path: /mnt/torrent
        state: directory
        mode: 777
